-- BaseDatos.sql — esquema y datos de los casos de uso 1 a 3 del enunciado (PostgreSQL 17).
-- La aplicación crea el esquema sola con Flyway (backend/src/main/resources/db/migration);
-- este script sirve para crear la base manualmente:  psql -h localhost -p 5433 -U banco -d banco -f BaseDatos.sql
-- Los movimientos (caso 4) se registran por la API, que aplica las reglas de saldo y cupo diario.

DROP TABLE IF EXISTS movimiento, cuenta, cliente, persona, flyway_schema_history CASCADE;

CREATE TABLE persona (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(100) NOT NULL,
    genero         VARCHAR(10)  NOT NULL CONSTRAINT ck_persona_genero CHECK (genero IN ('MASCULINO', 'FEMENINO', 'OTRO')),
    edad           INTEGER      NOT NULL CONSTRAINT ck_persona_edad CHECK (edad BETWEEN 0 AND 120),
    identificacion VARCHAR(13)  NOT NULL CONSTRAINT uk_persona_identificacion UNIQUE,
    direccion      VARCHAR(200) NOT NULL,
    telefono       VARCHAR(15)  NOT NULL
);

CREATE TABLE cliente (
    persona_id BIGINT       PRIMARY KEY CONSTRAINT fk_cliente_persona REFERENCES persona (id) ON DELETE CASCADE,
    cliente_id VARCHAR(20)  NOT NULL CONSTRAINT uk_cliente_cliente_id UNIQUE,
    contrasena VARCHAR(100) NOT NULL,
    estado     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE cuenta (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta      VARCHAR(20)    NOT NULL CONSTRAINT uk_cuenta_numero_cuenta UNIQUE,
    tipo_cuenta        VARCHAR(10)    NOT NULL CONSTRAINT ck_cuenta_tipo CHECK (tipo_cuenta IN ('AHORROS', 'CORRIENTE')),
    saldo_inicial      NUMERIC(19, 2) NOT NULL CONSTRAINT ck_cuenta_saldo_inicial CHECK (saldo_inicial >= 0),
    saldo_disponible   NUMERIC(19, 2) NOT NULL CONSTRAINT ck_cuenta_saldo_disponible CHECK (saldo_disponible >= 0),
    estado             BOOLEAN        NOT NULL DEFAULT TRUE,
    cliente_persona_id BIGINT         NOT NULL CONSTRAINT fk_cuenta_cliente REFERENCES cliente (persona_id),
    version            BIGINT         NOT NULL DEFAULT 0
);

CREATE INDEX idx_cuenta_cliente ON cuenta (cliente_persona_id);

CREATE TABLE movimiento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo_movimiento VARCHAR(10)    NOT NULL CONSTRAINT ck_movimiento_tipo CHECK (tipo_movimiento IN ('DEPOSITO', 'RETIRO')),
    valor           NUMERIC(19, 2) NOT NULL,
    saldo           NUMERIC(19, 2) NOT NULL CONSTRAINT ck_movimiento_saldo CHECK (saldo >= 0),
    cuenta_id       BIGINT         NOT NULL CONSTRAINT fk_movimiento_cuenta REFERENCES cuenta (id),
    -- crédito positivo, débito negativo
    CONSTRAINT ck_movimiento_signo CHECK (
        (tipo_movimiento = 'DEPOSITO' AND valor > 0) OR (tipo_movimiento = 'RETIRO' AND valor < 0)
    )
);

-- Soporta: último movimiento de la cuenta, cupo diario y reporte por rango de fechas
CREATE INDEX idx_movimiento_cuenta_fecha ON movimiento (cuenta_id, fecha DESC, id DESC);

-- Contraseñas 1234, 5678 y 1245 en BCrypt
INSERT INTO persona (id, nombre, genero, edad, identificacion, direccion, telefono) VALUES
    (1, 'Jose Lema',          'MASCULINO', 35, '1712345678', 'Otavalo sn y principal', '098254785'),
    (2, 'Marianela Montalvo', 'FEMENINO',  30, '1712345679', 'Amazonas y NNUU',        '097548965'),
    (3, 'Juan Osorio',        'MASCULINO', 40, '1712345680', '13 junio y Equinoccial', '098874587');

INSERT INTO cliente (persona_id, cliente_id, contrasena, estado) VALUES
    (1, 'jlema',     '$2a$10$8lVqVvbDwO0NWMDgfG6zFeZS.XvakTFNvuXsbmKoHI/AzCxH55Ww2', TRUE),
    (2, 'mmontalvo', '$2a$10$tTQbU/BqzEgWo6fOTsrJqOe6ZHSB8ng1.rQ15PWnjhbM8SfOwpTKu', TRUE),
    (3, 'josorio',   '$2a$10$rW8gm65NY1druSmZBq5RKuO.4tkUk.2.R4tWK85nAjQHEnwhhupgO', TRUE);

INSERT INTO cuenta (id, numero_cuenta, tipo_cuenta, saldo_inicial, saldo_disponible, estado, cliente_persona_id) VALUES
    (1, '478758', 'AHORROS',   2000.00, 2000.00, TRUE, 1),
    (2, '225487', 'CORRIENTE',  100.00,  100.00, TRUE, 2),
    (3, '495878', 'AHORROS',      0.00,    0.00, TRUE, 3),
    (4, '496825', 'AHORROS',    540.00,  540.00, TRUE, 2),
    (5, '585545', 'CORRIENTE', 1000.00, 1000.00, TRUE, 1);

SELECT setval(pg_get_serial_sequence('persona', 'id'), (SELECT max(id) FROM persona));
SELECT setval(pg_get_serial_sequence('cuenta', 'id'), (SELECT max(id) FROM cuenta));
