CREATE TABLE persona (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(100) NOT NULL,
    genero         VARCHAR(10)  NOT NULL CONSTRAINT ck_persona_genero CHECK (genero IN ('MASCULINO', 'FEMENINO', 'OTRO')),
    edad           INTEGER      NOT NULL CONSTRAINT ck_persona_edad CHECK (edad BETWEEN 0 AND 120),
    identificacion VARCHAR(13)  NOT NULL CONSTRAINT uk_persona_identificacion UNIQUE,
    direccion      VARCHAR(200) NOT NULL,
    telefono       VARCHAR(15)  NOT NULL
);

CREATE TABLE cliente (
    persona_id BIGINT       PRIMARY KEY CONSTRAINT fk_cliente_persona REFERENCES persona (id) ON DELETE CASCADE,
    cliente_id VARCHAR(20)  NOT NULL CONSTRAINT uk_cliente_cliente_id UNIQUE,
    contrasena VARCHAR(100) NOT NULL,
    estado     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE cuenta (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero_cuenta      VARCHAR(20)    NOT NULL CONSTRAINT uk_cuenta_numero_cuenta UNIQUE,
    tipo_cuenta        VARCHAR(10)    NOT NULL CONSTRAINT ck_cuenta_tipo CHECK (tipo_cuenta IN ('AHORROS', 'CORRIENTE')),
    saldo_inicial      NUMERIC(19, 2) NOT NULL CONSTRAINT ck_cuenta_saldo_inicial CHECK (saldo_inicial >= 0),
    saldo_disponible   NUMERIC(19, 2) NOT NULL CONSTRAINT ck_cuenta_saldo_disponible CHECK (saldo_disponible >= 0),
    estado             BOOLEAN        NOT NULL DEFAULT TRUE,
    cliente_persona_id BIGINT         NOT NULL CONSTRAINT fk_cuenta_cliente REFERENCES cliente (persona_id),
    version            BIGINT         NOT NULL DEFAULT 0
);

CREATE INDEX idx_cuenta_cliente ON cuenta (cliente_persona_id);

CREATE TABLE movimiento (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha           TIMESTAMP WITH TIME ZONE NOT NULL,
    tipo_movimiento VARCHAR(10)    NOT NULL CONSTRAINT ck_movimiento_tipo CHECK (tipo_movimiento IN ('DEPOSITO', 'RETIRO')),
    valor           NUMERIC(19, 2) NOT NULL,
    saldo           NUMERIC(19, 2) NOT NULL CONSTRAINT ck_movimiento_saldo CHECK (saldo >= 0),
    cuenta_id       BIGINT         NOT NULL CONSTRAINT fk_movimiento_cuenta REFERENCES cuenta (id),
    -- crédito positivo, débito negativo
    CONSTRAINT ck_movimiento_signo CHECK (
        (tipo_movimiento = 'DEPOSITO' AND valor > 0) OR (tipo_movimiento = 'RETIRO' AND valor < 0)
    )
);

-- Soporta: último movimiento de la cuenta, cupo diario y reporte por rango de fechas
CREATE INDEX idx_movimiento_cuenta_fecha ON movimiento (cuenta_id, fecha DESC, id DESC);
